import type { NextPage } from "next";
import Head from "next/head";
import Journal from "../components/journal";
import Sidebar from "../components/sidebar";
// import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  // const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex bg-amber-100 noisy">
        <Sidebar />
        <div className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
          <Journal />
        </div>
      </main>
    </>
  );
};

export default Home;
