import type { NextPage } from "next";
import { useRouter } from "next/router";
import Head from "next/head";
import Journal from "../components/journal";
import Sidebar from "../components/sidebar";
import { trpc } from "../utils/trpc";

type routerParams = {
  eid?: string;
};

const Write: NextPage = () => {
  const router = useRouter();
  const { eid }: routerParams = router.query;
  let res;

  if (eid) {
    res = trpc.useQuery([
      "journal-entry.single-journal-entry",
      { journalEntryId: eid },
    ]);
  }
  return (
    <>
      <Head>
        <title>Action Journal</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex bg-paper noisy brightness-125">
        <Sidebar />
        <div className="container mx-auto flex flex-col items-center justify-center min-h-screen p-9">
          <Journal data={res?.data} />
        </div>
      </main>
    </>
  );
};

export default Write;
