import { ReactNode } from "react";
import type { NextPage } from "next";
import Head from "next/head";
// import { LightBulbIcon } from "@heroicons/react/24/outline";
import Sidebar from "../components/sidebar";
import Header from "./header";

type LayoutProps = {
  children: ReactNode;
};

const Layout: NextPage<LayoutProps> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Action Journal</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className="flex flex-row
        h-full bg-paper dark:bg-slate-800 noisy brightness-125"
      >
        <Sidebar />
        {/* <LightBulbIcon className="h-8 w-8 flex-shrink-0 mr-3" /> */}
        <div className="flex flex-col w-full">
          <Header />
          {children}
        </div>
      </main>
    </>
  );
};

export default Layout;
