import { ReactNode } from "react";
import type { NextPage } from "next";
import Head from "next/head";
// import { LightBulbIcon } from "@heroicons/react/24/outline";
// import Sidebar from "../components/sidebar";
import Header from "./header";

type LayoutProps = {
  children: ReactNode;
};

const Layout: NextPage<LayoutProps> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Action Journal</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className="bg-paper dark:bg-black after:noisy"
        id="scrolling-container"
      >
        {/* <Sidebar /> */}
        <main className="flex w-full h-full min-h-screen justify-center">
          {children}
        </main>
        <Header />
      </div>
    </>
  );
};

export default Layout;
